### ISSUE TITLE
Top Gear recommending invalid gear

### ISSUE THREAD

**Issue by Valinora** [Voulk/QuestionablyEpic#1055]
Recommends I equip a plate belt as an upgrade as a druid. [SimC Paste](https://gist.github.com/Valinora/b5452f0fa81e90889e76b8b9d1f6b0ac)

Ideal behavior: filtering unwearable gear even if the user selects it for comparison

**Comment by Voulk** [comment]
Thanks. Gear that doesn't match your spec shouldn't appear for selection. I'll fix.
