### ISSUE TITLE
Fix the ilvl range of Dreadfire Vessel in the trinket chart

### ISSUE THREAD

**Issue by truchonh** [Voulk/QuestionablyEpic#776]
Hi, this is in theory a simple fix in the item database. 

When testing it localy, it did move the trinket just above construct core at max ilvl. It is a bigger difference than I expected, so I have some doubts about the fix. I dont own either of these trinkets at max ilvl so it's difficult for me to verify.

This is where it sits with a druid character (no simc import) and dungeon profile. (311: 259.5)
![image](https://user-images.githubusercontent.com/25945907/186510710-f44e4fbf-8c21-4476-b746-21c5f1ed9a6f.png)

Anyways, feel free to close the issue if this was addressed already. I can make a PR for it, but I'm sure you know where to change the ilvl numbers :p

**Comment by Voulk** [comment]
Great catch, I'll put through a fix for this now. Thanks!
